/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/StackLayout`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screen)'}/homeScreen` | `/homeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screen)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screen)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screen)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screen)'}/signupScreen` | `/signupScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screen)'}/splashScreen` | `/splashScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screen)'}/taskDetail` | `/taskDetail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screen)'}/taskScreen` | `/taskScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/StackLayout`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screen)'}/homeScreen` | `/homeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screen)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screen)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screen)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screen)'}/signupScreen` | `/signupScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screen)'}/splashScreen` | `/splashScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screen)'}/taskDetail` | `/taskDetail`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screen)'}/taskScreen` | `/taskScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/StackLayout${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(screen)'}/homeScreen${`?${string}` | `#${string}` | ''}` | `/homeScreen${`?${string}` | `#${string}` | ''}` | `${'/(screen)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(screen)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(screen)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(screen)'}/signupScreen${`?${string}` | `#${string}` | ''}` | `/signupScreen${`?${string}` | `#${string}` | ''}` | `${'/(screen)'}/splashScreen${`?${string}` | `#${string}` | ''}` | `/splashScreen${`?${string}` | `#${string}` | ''}` | `${'/(screen)'}/taskDetail${`?${string}` | `#${string}` | ''}` | `/taskDetail${`?${string}` | `#${string}` | ''}` | `${'/(screen)'}/taskScreen${`?${string}` | `#${string}` | ''}` | `/taskScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/StackLayout`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screen)'}/homeScreen` | `/homeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screen)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screen)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screen)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screen)'}/signupScreen` | `/signupScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screen)'}/splashScreen` | `/splashScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screen)'}/taskDetail` | `/taskDetail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screen)'}/taskScreen` | `/taskScreen`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
